Add diagnostics for semicolon at the end of function
This change introduce diagnostics when there is a semicolon at
the end of the function body:
```cpp
g: () = {};
```
Generates:
```
error: a compound function body shall not end with a semicolon (at ';')
```
And
```cpp
g: () = 42;;
```
Generates:
```
error: a short function syntax shall end with a single semicolon (at ';')
```