Add diagnostics for semicolon at the end of while body
This change introduce diagnostics when there is a semicolon at
the end of the while loop body:
```cpp
  i := 0;
  while i* < container.size() next i++ {
    std::cout << container[i] << std::endl;
  };
```
generates:
```
error: while loop body shall not end with a semicolon (at ';')
```