Add diagnostics for semicolon at the end of for loop
This change introduce diagnostics when there is a semicolon at
the end of the for..do loop body:
```cpp
  for v* | all next log() do :(e) = {
    foo();
    bar*;
  };
```
generates:
```
error: for..do loop body shall not end with a semicolon (at ';')
```