Add diagnostics for empty statements (extra semicolon)
This change introduce diagnostics when there is a semicolon
without statement
```cpp
;
```
Generates:
```
error: empty statement is not allowed - remove extra semicolon (at ';')
```
That also handles cases when there is double semicolon after a proper
statemnt:
```cpp
  i := 0;;
```
Generates:
```
error: empty statement is not allowed - remove extra semicolon (at ';')
```