Re-run regression tests
There seems to be a problem for MSVC here with "cpp2regex.h2(591): error C2668: 'std::make_reverse_iterator': ambiguous call to overloaded function". Here's 591:

    r := func(make_reverse_iterator(cur), make_reverse_match_context(ctx), true_end_func());

It seems the similar line 577 should also get this error, but doesn't because maybe that one is never invoked?

Conjecture: Maybe

- lines 577 and 591 make*iterator calls should be std:: qualified, and

- the make*iterator helpers on lines 184-189 should just be removed as they don't seem to be used?

But I'm not sure so I'll just push this update to regression tests in without any code changes