Fix parsing of string literals that contains //, closes #442 (#444)
In the following code:
```cpp
main: () = {
	{ std::cout << "//456"; } //error

	:()->_ = { return "//Error"; };

	b:="/* error even without {} block";
}
error: (x) -> _ = { return "//"; }
```
`//` and `/*` inside string literals are parsed as begining of comments.

Current change solves that. The missing is handling of raw string literals.

Closes #442