Add diagnostics for bad semicolons errors, closes #352 (#362)
* Add diagnostics for semicolon at the end of function

This change introduce diagnostics when there is a semicolon at
the end of the function body:
```cpp
g: () = {};
```
Generates:
```
error: a compound function body shall not end with a semicolon (at ';')
```
And
```cpp
g: () = 42;;
```
Generates:
```
error: a short function syntax shall end with a single semicolon (at ';')
```

* Add diagnostics for semicolon at the end of for loop

This change introduce diagnostics when there is a semicolon at
the end of the for..do loop body:
```cpp
  for v* | all next log() do :(e) = {
    foo();
    bar*;
  };
```
generates:
```
error: for..do loop body shall not end with a semicolon (at ';')
```

* Add diagnostics for semicolon at the end of while body

This change introduce diagnostics when there is a semicolon at
the end of the while loop body:
```cpp
  i := 0;
  while i* < container.size() next i++ {
    std::cout << container[i] << std::endl;
  };
```
generates:
```
error: while loop body shall not end with a semicolon (at ';')
```

* Add diagnostics for double semicolon at short lambda

This change introduce diagnostics when there is a double semicolon at
the end of the short function body for unnamed function:
```cpp
  l2 := :() -> int = 24;;
```
Generates:
```
error: a short function syntax shall end with a single semicolon (at ';')
```

* Add diagnostics for empty statements (extra semicolon)

This change introduce diagnostics when there is a semicolon
without statement
```cpp
;
```
Generates:
```
error: empty statement is not allowed - remove extra semicolon (at ';')
```
That also handles cases when there is double semicolon after a proper
statemnt:
```cpp
  i := 0;;
```
Generates:
```
error: empty statement is not allowed - remove extra semicolon (at ';')
```

* Fix error() method that throws when done() is true

When done() is true last correct token and its position is printed.