Add diagnostics for double semicolon at short lambda
This change introduce diagnostics when there is a double semicolon at
the end of the short function body for unnamed function:
```cpp
  l2 := :() -> int = 24;;
```
Generates:
```
error: a short function syntax shall end with a single semicolon (at ';')
```