Add diagnostics for type alias to a wildcard, closes #357 (#360)
In the current implementation of cppfront (f83ca9) the following code:
```cpp
alias5: type == _;
alias6: type == auto;
```
Generates succesfuly:
```cpp
using alias5 = auto;
using alias6 = auto;
```
Which is invalid cpp1 code.

After this change the alias to wildcard will generate the following error:
```
error: a 'type ==' alias declaration must be followed by a type name (not a wildcard _ nor auto)
```

All regression tests pass. Closes #357