Add diagnostics for unused literal or identifier, closes #364 (#365)
In compount statement when there is an literal or identifier
followed by semicolon it is treated as unused.
For the following code:
```cpp
    x;
```
The following error is reported:
```
error: unused literal or identifier (at 'x')
```